const {test}=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs/promises');const os=require('node:os');const path=require('node:path');const E=require('../engine.cjs');
const source=process.env.ORCA_FIXTURE;
if(!source)throw Error('Set ORCA_FIXTURE to an unmodified web/flutter_web folder.');
const themePromise=fs.readFile(path.join(__dirname,'..','theme.js'),'utf8');
async function fixture(t){const root=await fs.mkdtemp(path.join(os.tmpdir(),'orca-dark-test-'));t.after(()=>fs.rm(root,{recursive:true,force:true}));const bundle=path.join(root,'bundle'),target=path.join(root,'user','flutter_web'),store=path.join(root,'launcher');await fs.mkdir(bundle);for(const f of [...E.FILES,'version.json']){await fs.mkdir(path.dirname(path.join(bundle,f)),{recursive:true});await fs.copyFile(path.join(source,f),path.join(bundle,f));}return{bundle,target,store,theme:await themePromise,check:async()=>false};}
async function digest(dir){return Promise.all(E.FILES.map(async f=>E.hash(await fs.readFile(path.join(dir,f)))));}
test('apply, repeat, restore exact originals; preserve version and extra user files',async t=>{const a=await fixture(t);await fs.mkdir(a.target,{recursive:true});await fs.cp(a.bundle,a.target,{recursive:true});await fs.writeFile(path.join(a.target,'custom-note.txt'),'retain');const original=await digest(a.target),v=await fs.readFile(path.join(a.target,'version.json'),'utf8');await E.apply(a);assert.notDeepEqual(await digest(a.target),original);assert.match((await E.apply(a)).message,/already/);assert.equal(await fs.readFile(path.join(a.target,'version.json'),'utf8'),v);await E.restore(a);assert.deepEqual(await digest(a.target),original);assert.equal(await fs.readFile(path.join(a.target,'custom-note.txt'),'utf8'),'retain');assert.equal(await E.exists(path.join(a.target,E.MARKER)),false);});
test('reinstall web overwrite is repaired and original bundle remains unchanged',async t=>{const a=await fixture(t),original=await digest(a.bundle);await E.apply(a);await fs.rm(a.target,{recursive:true});await fs.cp(a.bundle,a.target,{recursive:true});await E.apply(a);assert.notDeepEqual(await digest(a.target),original);assert.deepEqual(await digest(a.bundle),original);});
test('new bundled resources supersede older target before patching',async t=>{const a=await fixture(t);await fs.mkdir(a.target,{recursive:true});await fs.cp(a.bundle,a.target,{recursive:true});const v=await E.version(a.target);v.build_number='20200101000000';await fs.writeFile(path.join(a.target,'version.json'),JSON.stringify(v));await fs.writeFile(path.join(a.target,'main.dart.js'),'old build');await E.apply(a);assert.equal((await E.version(a.target)).build_number,(await E.version(a.bundle)).build_number);});
test('unsupported newer user build is kept byte-for-byte',async t=>{const a=await fixture(t);await fs.mkdir(a.target,{recursive:true});await fs.cp(a.bundle,a.target,{recursive:true});const v=await E.version(a.target);v.build_number='20990101000000';await fs.writeFile(path.join(a.target,'version.json'),JSON.stringify(v));await fs.writeFile(path.join(a.target,'main.dart.js'),'unknown newer build');const before=await digest(a.target);await assert.rejects(E.apply(a),/not supported/);assert.deepEqual(await digest(a.target),before);});
test('restore refuses modified patched files and cannot downgrade official replacement',async t=>{const a=await fixture(t);await E.apply(a);await fs.appendFile(path.join(a.target,'main.dart.js'),'\nchanged');await assert.rejects(E.restore(a),/changed after/);await fs.rm(a.target,{recursive:true});await fs.cp(a.bundle,a.target,{recursive:true});await fs.writeFile(path.join(a.target,'main.dart.js'),'new official build');assert.match((await E.restore(a)).message,/No launcher patch/);assert.equal(await fs.readFile(path.join(a.target,'main.dart.js'),'utf8'),'new official build');});
test('running Orca blocks writes, including a launch during staging',async t=>{const a=await fixture(t);await assert.rejects(E.apply({...a,check:async()=>true}),/Quit/);assert.equal(await E.exists(a.target),false);let n=0;await assert.rejects(E.apply({...a,check:async()=>++n>=2}),/Quit/);assert.equal(await E.exists(a.target),false);});
test('Windows resource path discovery supports resources next to executable',async t=>{const a=await fixture(t),exe=path.join(path.dirname(a.bundle),'Snapmaker_Orca.exe');await fs.writeFile(exe,'test executable placeholder');const dir=path.join(path.dirname(exe),'resources','web','flutter_web');await fs.mkdir(dir,{recursive:true});await fs.cp(a.bundle,dir,{recursive:true});assert.equal(await E.appBundle(exe,'win32'),dir);});
test('version metadata drift blocks restoration',async t=>{const a=await fixture(t);await E.apply(a);const v=await E.version(a.target);v.build_number='20990101000000';await fs.writeFile(path.join(a.target,'version.json'),JSON.stringify(v));await assert.rejects(E.restore(a),/version changed/);assert.equal((await E.version(a.target)).build_number,v.build_number);});
test('interrupted folder swap recovers before reapplying',async t=>{const a=await fixture(t);await E.apply(a);const old=path.join(path.dirname(a.target),'.orca-dark-old-recovery'),stage=path.join(path.dirname(a.target),'.orca-dark-stage-recovery');await fs.rename(a.target,old);await fs.mkdir(stage);await fs.writeFile(path.join(a.store,'transaction.json'),JSON.stringify({target:a.target,old,stage}));await E.apply(a);assert.equal(await E.exists(a.target),true);assert.equal(await E.exists(old),false);assert.equal(await E.exists(stage),false);assert.equal(await E.exists(path.join(a.store,'transaction.json')),false);});
test('an earlier three-file launcher patch upgrades and still restores icons',async t=>{const a=await fixture(t);const original=await digest(a.bundle);await E.apply(a);const marker=path.join(a.target,E.MARKER),m=JSON.parse(await fs.readFile(marker,'utf8'));const legacy=E.hash('legacy-'+m.backup);await fs.rename(path.join(a.store,'backups',m.backup),path.join(a.store,'backups',legacy));m.backup=legacy;for(const f of E.FILES.slice(3)){delete m.patched[f];await fs.copyFile(path.join(a.bundle,f),path.join(a.target,f));await fs.unlink(path.join(a.store,'backups',legacy,f));}await fs.writeFile(marker,JSON.stringify(m));await E.apply(a);await E.restore(a);assert.deepEqual(await digest(a.target),original);});

test('Windows selection accepts a differently named EXE with actual Orca resources',async t=>{const a=await fixture(t),root=path.dirname(a.bundle),exe=path.join(root,'orca-slicer.exe');await fs.writeFile(exe,'fixture');const dir=path.join(root,'resources','web','flutter_web');await fs.cp(a.bundle,dir,{recursive:true});assert.equal(await E.appBundle(exe,'win32'),dir);});
test('downloaded EXE without installed resources is refused clearly',async t=>{const a=await fixture(t),exe=path.join(path.dirname(a.bundle),'setup.exe');await fs.writeFile(exe,'fixture');await assert.rejects(E.appBundle(exe,'win32'),/no Orca web resources/);});
test('Windows process guard follows the selected executable name',()=>{assert.equal(E.matchesWindowsProcess('"orca-slicer.exe","1234","Console","1","1 K"','C:\\Program Files\\Snapmaker Orca\\orca-slicer.exe'),true);assert.equal(E.matchesWindowsProcess('"other.exe","1234"','C:\\Apps\\orca-slicer.exe'),false);assert.equal(E.matchesWindowsProcess('"Snapmaker_Orca.exe","1234"'),true);});
test('choosing the installation folder resolves the Orca executable',async t=>{const a=await fixture(t),root=path.dirname(a.bundle),exe=path.join(root,'snapmaker-orca.exe');await fs.writeFile(exe,'fixture');await fs.writeFile(path.join(root,'uninstall-orca.exe'),'fixture');await fs.cp(a.bundle,path.join(root,'resources','web','flutter_web'),{recursive:true});assert.equal(await E.executableInFolder(root),exe);});
test('ambiguous installation folder requires an explicit executable choice',async t=>{const a=await fixture(t),root=path.dirname(a.bundle);for(const name of ['orca-slicer.exe','Snapmaker_Orca.exe'])await fs.writeFile(path.join(root,name),'fixture');await fs.cp(a.bundle,path.join(root,'resources','web','flutter_web'),{recursive:true});await assert.rejects(E.executableInFolder(root),/More than one/);});
test('corrupted existing backup is rejected before applying again',async t=>{const a=await fixture(t);await E.apply(a);const marker=JSON.parse(await fs.readFile(path.join(a.target,E.MARKER),'utf8'));await E.restore(a);await fs.writeFile(path.join(a.store,'backups',marker.backup,'index.html'),'damaged');const before=await digest(a.target);await assert.rejects(E.apply(a),/backup is damaged/);assert.deepEqual(await digest(a.target),before);});
test('source edits during staging abort without overwriting user changes',async t=>{const a=await fixture(t);await fs.cp(a.bundle,a.target,{recursive:true});let checks=0;await assert.rejects(E.apply({...a,check:async()=>{if(++checks===2)await fs.writeFile(path.join(a.target,'user-added.txt'),'preserve');return false;}}),/changed during preparation/);assert.equal(await fs.readFile(path.join(a.target,'user-added.txt'),'utf8'),'preserve');assert.equal(await E.exists(path.join(a.target,E.MARKER)),false);});
test('linked resource files are refused without touching their destination',async t=>{const a=await fixture(t);await fs.cp(a.bundle,a.target,{recursive:true});const outside=path.join(path.dirname(a.store),'outside.txt');await fs.writeFile(outside,'preserve');await fs.symlink(outside,path.join(a.target,'linked'));await assert.rejects(E.apply(a),/Linked web resources/);assert.equal(await fs.readFile(outside,'utf8'),'preserve');});
test('inspection validates hashes instead of trusting the version label',async t=>{const a=await fixture(t);await fs.cp(a.bundle,a.target,{recursive:true});await fs.appendFile(path.join(a.target,'main.dart.js'),'changed');await assert.rejects(E.inspect(a),/not supported/);});
test('interrupted first installation can recover without an existing target',async t=>{const a=await fixture(t);await fs.mkdir(a.store,{recursive:true});const parent=path.dirname(a.target);await fs.mkdir(parent,{recursive:true});const stage=path.join(parent,'.orca-dark-stage-initial'),old=path.join(parent,'.orca-dark-old-initial');await fs.mkdir(stage);await fs.writeFile(path.join(a.store,'transaction.json'),JSON.stringify({target:a.target,stage,old,hadTarget:false}));await E.apply(a);assert.equal(await E.exists(path.join(a.target,E.MARKER)),true);});
