const {test}=require('node:test');const assert=require('node:assert/strict');const vm=require('node:vm');const fs=require('node:fs');const path=require('node:path');
const code=fs.readFileSync(path.join(__dirname,'../ui/renderer.js'),'utf8');
async function setup(overrides={}){
 const elements=new Map();const get=id=>{if(!elements.has(id))elements.set(id,{textContent:'',disabled:false,classList:{toggle(){}},addEventListener(type,fn){this[type]=fn;}});return elements.get(id);};
 const calls=[];const launcher={state:async()=>({appPath:'C:\\Program Files\\Snapmaker Orca\\Snapmaker_Orca.exe',running:true,autoOpen:false}),action:async a=>{calls.push(a);throw Error('Quit Snapmaker Orca first, then try again.');},choose:async()=>({canceled:false}),onNotice(){},...overrides};
 vm.runInNewContext(code,{document:{getElementById:get},window:{launcher},setInterval(){}});await new Promise(resolve=>setImmediate(resolve));return{get,calls};
}
test('Apply remains clickable while Orca runs and explains refusal',async()=>{const {get,calls}=await setup();assert.equal(get('launch').disabled,false);assert.match(get('availability').textContent,/Close it before applying/);await get('launch').click();assert.deepEqual(calls,['launch']);assert.match(get('status').textContent,/Quit Snapmaker Orca/);assert.equal(get('launch').disabled,false);});
test('Apply does not wait on a stalled status poll before starting',async()=>{let invoked=false;const {get}=await setup({state:()=>new Promise(()=>{}),action:async()=>{invoked=true;return{message:'Applied'};}});get('apply').click();await new Promise(resolve=>setImmediate(resolve));assert.equal(invoked,true);assert.equal(get('status').textContent,'Applied');});
test('choosing the same installation visibly acknowledges the choice',async()=>{const{get}=await setup();await get('choose').click();assert.match(get('status').textContent,/Installation selected/);});
test('file and unsupported-build errors remain visible after refreshing state',async()=>{const{get}=await setup({action:async()=>{throw Error('This Orca web build is not supported yet. Nothing changed.');}});await get('apply').click();assert.match(get('status').textContent,/not supported/);assert.equal(get('apply').disabled,false);});
test('Apply stays clickable when detection has not found an installation',async()=>{const {get}=await setup({state:async()=>({appPath:'',running:false}),action:async()=>{throw Error('Choose your Snapmaker Orca installation first.');}});assert.equal(get('apply').disabled,false);assert.equal(get('launch').disabled,false);await get('apply').click();assert.match(get('status').textContent,/Choose your Snapmaker Orca installation/);});

test('verified theme stays successful after Apply opens Orca',async()=>{let current=false,running=false;const {get}=await setup({state:async()=>({appPath:'/Orca.app',current,running}),action:async()=>{current=true;running=true;return{message:'Dark mode applied. Orca launch requested.'};}});await get('launch').click();await new Promise(resolve=>setImmediate(resolve));assert.match(get('availability').textContent,/Dark theme is applied/);assert.match(get('availability').textContent,/You can close Snorca After Dark/);assert.doesNotMatch(get('availability').textContent,/before applying/);assert.match(get('status').textContent,/Dark mode applied/);});
test('compatibility problems take precedence over a current marker',async()=>{const {get}=await setup({state:async()=>({appPath:'/Orca.app',current:true,running:true,problem:'Resources changed. Inspect before applying.'})});assert.match(get('availability').textContent,/Resources changed/);});
