const {test}=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs/promises'),path=require('node:path'),os=require('node:os');
const {SettingsStore,OperationGate,Diagnostics}=require('../runtime.cjs');
async function folder(t){const dir=await fs.mkdtemp(path.join(os.tmpdir(),'snorca-runtime-'));t.after(()=>fs.rm(dir,{recursive:true,force:true}));return dir;}
test('concurrent preference saves are serialized and both changes survive',async t=>{const dir=await folder(t),s=new SettingsStore(dir);await s.load();await Promise.all([s.update({appPath:'C:\\Apps\\snapmaker-orca.exe'}),s.update({autoOpen:true})]);const reopened=new SettingsStore(dir);assert.equal(await reopened.load(),'');assert.equal(reopened.value.autoOpen,true);assert.match(reopened.value.appPath,/snapmaker-orca/);});
test('invalid settings are preserved and never auto launch',async t=>{const dir=await folder(t);await fs.writeFile(path.join(dir,'settings.json'),'{"appPath":7,"autoOpen":"true"}');const s=new SettingsStore(dir);assert.match(await s.load(),/copy was preserved/);assert.equal(s.value.autoOpen,false);await s.update({appPath:'new'});assert.equal((await fs.readdir(dir)).filter(x=>x.startsWith('settings.invalid-')).length,1);});
test('a rejected setting does not poison the save queue',async t=>{const s=new SettingsStore(await folder(t));await assert.rejects(s.update({autoOpen:'true'}),/invalid/);await s.update({autoOpen:true});assert.equal(s.value.autoOpen,true);});
test('gate rejects overlapping mutations and recovers after an error',async()=>{const gate=new OperationGate();let release;const operation=gate.run(()=>new Promise(r=>release=r));await assert.rejects(gate.run(async()=>{}),/already running/);release();await operation;await assert.rejects(gate.run(async()=>{throw Error('failure');}));assert.equal(await gate.run(async()=>42),42);});
test('diagnostic logs rotate and do not store arbitrary message contents',async t=>{const dir=await folder(t),d=new Diagnostics(dir);await fs.writeFile(path.join(dir,'diagnostics.log'),'x'.repeat(66000));await d.write('operation.error','EACCES');assert.equal((await fs.stat(path.join(dir,'diagnostics.log.1'))).size,66000);const row=JSON.parse(await fs.readFile(path.join(dir,'diagnostics.log'),'utf8'));assert.deepEqual(Object.keys(row),['time','event','code']);});
