const {test}=require('node:test'),assert=require('node:assert/strict');
const {Updates,eligibleRelease,WEEK}=require('../updates.cjs');
const config={repository:'example/sn orca'.replace(' ',''),channel:'stable',current:'1.9.0',platform:'win32',arch:'x64'};
function release(version,{prerelease=false,draft=false,arch='x64',url}={}){return{tag_name:'v'+version,prerelease,draft,assets:[{name:`Snorca-After-Dark-Setup-${version}-${arch}.exe`,browser_download_url:url||`https://github.com/${config.repository}/releases/download/v${version}/setup.exe`}]};}
test('updates compare numeric versions and never offer equal or older versions',()=>{assert.equal(eligibleRelease([release('1.10.0')],config).status,'available');for(const version of ['1.9.0','1.8.9'])assert.equal(eligibleRelease([release(version)],config).status,'current');});
test('updates filter wrong CPU, drafts, prereleases, malformed versions and foreign URLs',()=>{for(const r of [release('2.0.0',{arch:'arm64'}),release('2.0.0',{draft:true}),release('2.0.0-beta.1',{prerelease:true}),release('wat'),release('2.0.0',{url:'https://evil.example/setup.exe'})])assert.equal(eligibleRelease([r],config).status,'unavailable');});
function setup(fetcher){const settings={value:{automaticUpdates:true,lastUpdateAttempt:0,dismissedUpdate:''},async update(value){Object.assign(this.value,value);}};let clock=WEEK+1;const service=new Updates({settings,config,current:config.current,platform:'win32',arch:'x64',fetcher,now:()=>clock});return {service,settings,advance:()=>clock+=WEEK+1};}
test('weekly checks persist attempts, stay quiet for repeated offers, and allow manual checks',async()=>{let calls=0;const a=setup(async()=>{calls++;return{ok:true,text:async()=>JSON.stringify([release('1.10.0')])};});assert.equal((await a.service.check()).status,'available');assert.equal(await a.service.check(),null);a.advance();assert.equal(await a.service.check(),null);assert.equal((await a.service.check(true)).status,'available');assert.equal(calls,3);const reopened=new Updates({settings:a.settings,config,current:config.current,platform:'win32',arch:'x64',now:()=>a.settings.value.lastUpdateAttempt+1,fetcher:()=>{throw Error('must not fetch');}});assert.equal(await reopened.check(),null);});
test('disabled automatic checks keep manual checks available and errors are not up-to-date',async()=>{const a=setup(async()=>{throw Error('offline');});a.settings.value.automaticUpdates=false;assert.equal(await a.service.check(),null);assert.equal((await a.service.check(true)).status,'error');});
test('no publication channel is reported honestly and never contacts a server',async()=>{const a=setup(()=>{throw Error('must not fetch');});a.service.config={repository:null};assert.equal(await a.service.check(),null);assert.equal((await a.service.check(true)).status,'unconfigured');});
